### PR TITLE
Konshuu reader rewrite

### PR DESCRIPTION
**Pull request by jie-luo**

### CODE REVIEW

**Comment by jie-luo** [comment]
I find it strange that none of the libraries are included in .gitignore. To continue following this convention, I opted not to add any entries into .gitignore (for now).

**Comment by jie-luo** [comment]
I messed up and used `git rebase` instead of `git merge` thus adding an unnecessary 20 or so commits.

But hey at least I fixed the merge conflict!

**Comment by stsushi** [comment]
Sorry alot of these changes are small things that we should do but there are some larger issues that ll be inconvenient to merge in like the loss of the git history and if you change the upper format of the css that ll make it strange to comprehend why this file is differently formatted from the other index css's we are going to do a website overhaul and this is something we are going to look at but this would not help with eventual overhauls and such. I appreciate and will look into a lot of the smaller things like renaming the favicons to match normal convention, but for the reasons listed above we cant merge this into our code base! Thanks, though!

**Comment by jie-luo** [comment]
> Sorry alot of these changes are small things that we should do

No? I literally rewrote the entire konshuu reader. Deleted it and rewrote it from scratch. This is a feature implementation, not mere maintenance updates.

 >  loss of the git history

No git history was actually lost. The `git rebase` **duplicated** git history, which was why I force reverted it.

 > if you change the upper format of the css that ll make it strange to comprehend why this file is differently formatted from the other index css

What does this even mean? What are you talking about? Having two CSS files makes it more maintainable because then a tiny CSS change from the main doesn't accidentally bowl over the CSS of the konshuu reader especially since the reader so heavily depends on CSS in order to function.

 > we are going to do a website overhaul

Then do the website overhaul. I prototyped the reader without even realizing that the CAA github existed; I can assure you that this reader is just as easily moved around (if not more easily) as the current reader

**Comment by stsushi** [comment]
for now i dont think we want to move forward with this re-implementation of the konshuu reader, we already fixed the main issue that existed in it and the current one fits with both the style of konshuu as well as works as  basis for us to implement the new features that we add to it.  Thanks though for thinking about konshuu/caa though.

**Pull request closed without merging**
